serve:
  proxy:
    port: 4455
    trust_forwarded_headers: true
    cors:
      enabled: true
      allowed_origins:
        - https://ory-vault.test
        - https://app.ory-vault.test
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
  api:
    port: 4456

errors:
  fallback:
    - json

log:
  level: debug
  format: json

access_rules:
  matching_strategy: glob
  repositories:
    - file:///etc/config/oathkeeper/rules.yaml

authenticators:
  noop:
    enabled: true
  cookie_session:
    enabled: true
    config:
      check_session_url: https://vault-kratos:4433/sessions/whoami
      preserve_path: true
      preserve_query: true
      subject_from: identity.id
      extra_from: "@this"
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: http://vault-hydra:4445/admin/oauth2/introspect
      scope_strategy: wildcard

authorizers:
  allow:
    enabled: true
  remote_json:
    enabled: true
    config:
      remote: http://vault-keto:4466/check
      payload: |
        {
          "subject": "{{ print .Subject }}",
          "resource": "{{ print .MatchContext.RegexpCaptureGroups.index }}",
          "action": "{{ print .MatchContext.Method }}"
        }

mutators:
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: https://api.ory-vault.test/
      jwks_url: file:///etc/config/oathkeeper/jwks.json
      claims: |
        {
          "session": {{ .Extra | toJson }},
          "scp": {{ .Extra.scp | toJson }}
        }
  header:
    enabled: true
    config:
      headers:
        X-User-Id: "{{ .Subject }}"
