serve:
  proxy:
    port: 4455
    cors:
      enabled: true
      allowed_origins:
        - http://ory-vault.test
        - http://app.ory-vault.test
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
  api:
    port: 4456

errors:
  fallback:
    - json

log:
  level: debug
  format: json

access_rules:
  matching_strategy: glob
  repositories:
    - file:///etc/config/oathkeeper/rules.yaml

authenticators:
  noop:
    enabled: true
  cookie_session:
    enabled: true
    config:
      check_session_url: http://vault-kratos:4433/sessions/whoami
      preserve_path: true
      preserve_query: true
      subject_from: identity.id
      extra_from: "@this"

authorizers:
  allow:
    enabled: true
  remote_json:
    enabled: true
    config:
      remote: http://vault-keto:4466/check
      payload: |
        {
          "subject": "{{ print .Subject }}",
          "resource": "{{ print .MatchContext.RegexpCaptureGroups.index }}",
          "action": "{{ print .MatchContext.Method }}"
        }

mutators:
  noop:
    enabled: true
  header:
    enabled: true
    config:
      headers:
        X-User-Id: "{{ .Subject }}"
