selfservice:
  default_browser_return_url: http://ory-vault.test/
  allowed_return_urls:
    - http://ory-vault.test/
    - http://api.ory-vault.test/
  methods:
    password:
      enabled: true
  flows:
    error:
      ui_url: http://ory-vault.test/auth/error
    settings:
      ui_url: http://ory-vault.test/auth/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://ory-vault.test/auth/recovery
    verification:
      enabled: true
      ui_url: http://ory-vault.test/auth/verification
      after:
        default_browser_return_url: http://ory-vault.test/
    logout:
      after:
        default_browser_return_url: http://ory-vault.test/auth/login
    login:
      ui_url: http://ory-vault.test/auth/login
      lifespan: 10m
    registration:
      lifespan: 10m
      ui_url: http://ory-vault.test/auth/registration
      after:
        password:
          hooks:
            - hook: session

cookies:
  domain: ory-vault.test
  path: /
  same_site: Lax

session:
  cookie:
    domain: ory-vault.test
    path: /
    same_site: Lax
    persistent: true

secrets:
  cookie:
    - secret-cookie-exactly-32-chars-x
  cipher:
    - secret-cipher-exactly-32-chars-x

log:
  level: debug
  format: json

courier:
  smtp:
    connection_uri: smtp://vault-mailpit:1025/?skip_ssl_verify=true
    from_address: noreply@ory-vault.test
    from_name: ORY Vault DMS

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

serve:
  public:
    base_url: http://auth.ory-vault.test/
    cors:
      enabled: true
      allowed_origins:
        - http://ory-vault.test
        - http://app.ory-vault.test
        - http://api.ory-vault.test
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: http://vault-kratos:4434/

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
