server {
    listen 80;
    server_name auth.ory-vault.test;

    location / {
        proxy_pass http://vault-kratos:4433;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name api.ory-vault.test app.ory-vault.test;

    location / {
        proxy_pass http://vault-oathkeeper:4455;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name ory-vault.test;

    location / {
        proxy_pass http://vault-ui:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
