server {
    listen 80;
    server_name auth.ory-vault.test;

    location / {
        proxy_pass http://vault-kratos:4433;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cookie_flags ~.* domain=ory-vault.test;
        
        proxy_set_header Cookie $http_cookie; # TAMBAHKAN INI
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name api.ory-vault.test app.ory-vault.test;

    location / {
        proxy_pass http://vault-oathkeeper:4455;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header Cookie $http_cookie; # TAMBAHKAN INI
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Tambahkan ini untuk menangani Preflight CORS jika diperlukan
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://ory-vault.test' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Cookie' always;
            return 204;
        }
    }
}

server {
    listen 80;
    server_name ory-vault.test;

    location / {
        proxy_pass http://vault-ui:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        proxy_set_header Cookie $http_cookie; # TAMBAHKAN INI
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name mail.ory-vault.test;

    location / {
        proxy_pass http://vault-mailpit:8025;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        proxy_set_header Cookie $http_cookie; # TAMBAHKAN INI
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
